- R/eval_forecasts.R
- R/fun_probabilistic_forecast_binary.R
- R/fun_probabilstic_forecasts_integer.R
- README.md
- tests/testthat/test-eval_forecasts.R
- tests/testthat/test-eval_probabilstic_forecasts.R
- tests/testthat/test-fun_probabilistic_forecast_binary.R
- tests/testthat/test-fun_probabilstic_forecasts_integer.R
> Tests and error handling

- R/interval_score.R
See Eq. 1 in https://arxiv.org/abs/2005.12881
> only divide weighed interval score by 2

- .github/workflows/test-coverage.yaml
Adds back in functionality dropped in #57
> Adds support for GitHub actions test coverage

- R/bias.R
- R/metrics_point_forecasts.R
Solve issue mentioned in https://github.com/epiforecasts/scoringutils/issues/76
> Enable handling of missing median prediction

- DESCRIPTION
- NEWS.md
- R/zzz.R
- man/quantile_bias.Rd
@nickreich changed version number and added a message to the user
> Update version number to change wis definition

- R/bias.R
- R/eval_forecasts.R
- R/interval_score.R
- R/pivoting_functions.R
- man/quantile_bias.Rd
allows scoring of point forecasts where quantile is NA
> fix scoring of point forecasts

- DESCRIPTION
- NEWS.md
- R/eval_forecasts.R
- R/eval_forecasts_quantile.R
- R/interval_score.R
- R/zzz.R
- man/eval_forecasts.Rd
- man/interval_score.Rd
- tests/testthat/test-interval_score.R
moves the change in weighting of the median out of the `interval_score` function into `eval_forecasts()` where the summation happens.
> slight correction to change in WIS definition

- R/pairwise-comparisons.R
> improve error handling for pairwise comparisons

- NEWS.md
> update news file format

- R/pit.R
- man/hist_PIT.Rd
- man/pit_df.Rd
- tests/testthat/test-pit.R
Add a quantile version for PIT histograms to the pit_df() and hist_PIT() functions.
> add a quantile version to pit_df and hist_PIT

- README.Rmd
This PR contains slight edits and updates to the package README.
> README tidy

- _pkgdown.yml
as the title says attempts to fix index issue blocking pkgdown documentation from building
> fixes index for pkgdown

- R/pairwise-comparisons.R
- R/score.R
- inst/CITATION
Clean up documentation of ... parameters
> cleaning function documentation

- .github/workflows/render_readme.yaml
Action by @sbfnk to render the Readme from Readme.Rmd automatically
> render README action

- R/check-input-helpers.R
- R/get_-functions.R
- R/pairwise-comparisons.R
- R/score_quantile.R
- R/utils.R
- R/utils_data_handling.R
Does what it says on the tin. Except it probably doesn't fix all linting. The vignette R files are created automatically... 🥲
> Fix linting

- R/data.R
- R/metrics-quantile.R
- R/metrics-sample.R
- man/abs_error.Rd
- man/ae_median_quantile.Rd
- man/example_binary.Rd
- man/example_continuous.Rd
- man/example_point.Rd
- man/example_quantile.Rd
- man/example_quantile_forecasts_only.Rd
- man/example_truth_only.Rd
- man/interval_coverage.Rd
- man/interval_coverage_deviation_quantile.Rd
- man/metrics_quantile.Rd
- man/se_mean_sample.Rd
- man/wis.Rd
This PR 
- adds some error handling to `ae_median_quantile`, `ae_median_sample` and `se_mean_sample`
- updates some documentation
> Update functions to compute the absolute median

- R/metrics-quantile.R
- tests/testthat/test-metrics-quantile.R
- tests/testthat/test-sharpness.R
Add a few tests (mostly input checks) for binary and quantile-based metrics. 
Need to do more, but here's a start :)
> Expand tests2

- .github/workflows/render_readme.yaml
> Update render readme action in develop

- README.Rmd
- README.md
Somewhere along the various merge conflicts a `as_forecast()` statement got dropped from the Readme. This PR adds it back in.
> Fix readme

- tests/testthat/test-inputs-scoring-functions.R
This PR closes #703 
A few tests were not appearing in codecov. This was a great mystery to me until I realised that the test file had the wrong name... This PR fixes that (and also updates the test file structure slightly by moving shared code to the top).
> Issue #703: fix name of test file

- NEWS.md
- R/pairwise-comparisons.R
- tests/testthat/test-pairwise_comparison.R
This PR closes #637.
All instances of returning NULL and associated checks have been removed, and corresponding warnings replaced with errors.
> 637: Error in pairwise comparison

- R/plot.R
- tests/testthat/test-plot_wis.R
As "discussed" in #355 plotting functions are missing input checks. Since I am a good boy and would never do too many things in a single PR, this PR just adds a few input checks to `plot_wis()` + a test.
> Issue #355 - Add input checks to `plot_wis()`

- R/plot.R
Adds simple input checks to the coverage plot functions (making sure input is a data.frame and `colour` is a column of the data).
> Issue #355 - Add input checks to coverage plots

- tests/testthat/setup.R
This PR closes #450. It looks like these were no longer needed anyway and so no other changes appear to be needed.
> Issue 450: get rid of library calls in tests/setup.R

- NEWS.md
- R/metrics-quantile.R
- R/metrics-sample.R
- R/pit.R
- man/logs_sample.Rd
- man/pit_sample.Rd
- man/wis.Rd
- tests/testthat/test-forecast.R
- tests/testthat/test-get_correlations.R
- vignettes/Deprecated-functions.Rmd
This PR cleans up the stray half-sentence and new lines from a previous PR (#776) in the "Deprecated functions"-vignette. I also sprinkled in some spell-checking here and there :)
> Cosmetic changes and spell-checking

- NEWS.md
This PR closes #687. 
The PR reorganises the news items for the current major package update. 
- [ x My code follows the established coding standards and I have run `lintr::lint_package()` to check for style issues introduced by my changes.
> Issue #687 - Reorganise NEWS file before release

- R/documentation-templates.R
- R/forecast.R
- R/metrics-quantile.R
- man/as_forecast.Rd
- man/assert_forecast.Rd
- man/forecast_types.Rd
- man/get_forecast_unit.Rd
- man/score.Rd
- tests/testthat/test-metrics-quantile.R
This PR cleans up a few minor things:
- a typo in the docs
- missing `@rdname` statements
- a user message
> Clean a few minor things

- vignettes/Deprecated-visualisations.Rmd
This PR closes #812.
As discussed in #812, this PR now mentions hubVis in the vignette for deprecated visualisations.
In the future, we should work on a proper visualisations Vignette (see #713)
> Issue #812 - mention hubVis package in vignette

- R/check-inputs-scoring-functions.R
This PR closes #838.
As described #838 this PR makes the input check a bit more precise.
> Issue #838 - small fix to input checks

- README.Rmd
> Issue #861 - fix failing render readme

- R/metrics-quantile.R
- man/wis.Rd
> Issue #800 - Add formula and reference to WIS documentation

- R/default-scoring-rules.R
- man/get_metrics.forecast_point.Rd
- man/get_metrics.forecast_quantile.Rd
Small drive-by improvements of the docs.
> Improve function documentation for point forecasts

- R/summarise_scores.R
- tests/testthat/test-summarise_scores.R
Went ahead and just implemented the test I proposed
> Add test and fix bug

- R/z-packageStartupMessage.R
- R/zzz.R
> Update startup message and rename file to make clear what's inside

- tests/testthat/test-class-forecast-quantile.R
- tests/testthat/test-class-forecast.R
> Fix some warnings that appeared in tests

- R/check-input-helpers.R
- R/class-forecast-binary.R
- R/class-forecast.R
- R/class-scores.R
- R/documentation-templates.R
- R/forecast-unit.R
- R/get-correlations.R
- R/get-coverage.R
- R/get-duplicate-forecasts.R
- R/get-forecast-counts.R
- R/get-pit-histogram.R
- R/helper-quantile-interval-range.R
- R/metrics-binary.R
- R/metrics-nominal.R
- R/metrics-quantile.R
- R/metrics-sample.R
- R/metrics.R
- R/pairwise-comparisons.R
- R/plot-heatmap.R
- R/plot-wis.R
- R/score.R
- R/theme-scoringutils.R
- R/transform-forecasts.R
- vignettes/Deprecated-functions.Rmd
- vignettes/Deprecated-visualisations.Rmd
Apparently `return` is deprecated in favour of `returns`. Being a good boi here and updating our package docs.
> update `return` with the new `returns`

- DESCRIPTION
- NEWS.md
- R/metrics-sample.R
This PR closes #976.
As mentioned in the issue I used the opportunity to make under/overprediction calculation concise.
> 976: make under/overprediction calculation concise

- .github/workflows/R-CMD-check.yaml
- DESCRIPTION
- NEWS.md
This PR closes #999, which should fix failing checks.
> 999: update R dependency

- DESCRIPTION
- NEWS.md
This PR closes #<issue-number>.
> 1008: update scoringRules dependency

- .github/workflows/test-coverage.yaml
> 1012: specify codecov token in environment

- NEWS.md
- R/get-pit-histogram.R
- inst/manuscript/manuscript.Rmd
- inst/manuscript/manuscript.tex
- man/get_pit_histogram.Rd
> Issue #1018  - Fix missing labels in `labs() as required by new ggplot2 release
