NEWS.md, R/eval_forecasts.R
added 3 new metrics to `eval_forecasts`
- sharpness as percentage of true values that fall in a given interval range
- bias as transformed percentage of true values above and below the median
- sharpness as the mean width of the 50% interval range
=> added new metrics to quantile scoring: bias, sharpness, calibration

R/plot.R
plot currently errors if no truth data is available
=> fix plot predictions when no truth is available

DESCRIPTION, NEWS.md, R/eval_forecasts_binary.R, R/eval_forecasts_continuous_integer.R, R/eval_forecasts_quantile.R, tests/testthat/test-eval_forecasts.R, tests/testthat/test-interval_score.R
This PR
- fixes a bug where not selecting 'interval_score' as a metric when using quantile data resulted in an error
- fixes an unrelated small bug where for binary scores, the wrong data.frame was used to summarise scores
- creates a new unit test for the bug fix
- updates the version number and news file
=> Fix bug in metrics selection

R/eval_forecasts_helper.R, R/pairwise-comparisons.R, R/utils.R, _pkgdown.yml, man/add_quantiles.Rd, man/add_rel_skill_to_eval_forecasts.Rd, man/add_sd.Rd, man/check_equal_length.Rd, man/check_not_null.Rd, man/delete_columns.Rd, man/extract_from_list.Rd, man/geom_mean_helper.Rd, man/update_list.Rd
scoringutils exports a lot of functions and while I was trying to learn more about the package functionality, it was difficult to create mental categories of which function serves which purpose. In this PR, I make these categories explicit by creating a reference index for the pkgdown website.
I can revisit this PR as much as necessary, e.g., by adding a short description for each category. I also see that you are probably in the process of submitting to CRAN so feel free to delay merging this PR as you might not want to introduce extra sources of potential issues at the last minute. 
For reference, here is the relevant pkgdown help page where you can see all the options for the reference index: https://pkgdown.r-lib.org/reference/build_reference.html
A screenshot of the output:
=> Create pkgdown reference index

.github/workflows/rebase-comment.yaml
For security purposes, this is restricted to members of the epiforecasts organisation.
This PR follows the discussion in #107.
=> Add GitHub action to automatically rebase PR when a comment with '/rebase' is posted

R/pairwise-comparisons.R
This should fix https://github.com/epiforecasts/covid19-forecast-hub-europe/issues/1194 as identified by @Bisaloo
=> avoid mixture of NA and NaN

R/eval_forecasts_binary.R, R/eval_forecasts_continuous_integer.R, R/eval_forecasts_helper.R, R/eval_forecasts_quantile.R, R/utils_data_handling.R
Fixes a few (but not all) instances of #129
=> visible data.table return in a few functions

.Rbuildignore, .devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/library-scripts/common-debian.sh, .github/workflows/build-image.yaml
This PR adds a docker container (with alll dependencies etc + vscode dev tools) based on a rocker image. 
It also adds a github action to build this docker image and vscode config options to make spinning up a dev box easier (+ support for codespaces). 
This would all make my life easier but might also be nice for others. Very optional though as obvious has no impact on the core code.
=> Add docker + vscode support

.Rbuildignore, .gitignore, DESCRIPTION, _pkgdown.yml
Switches the package website to use bootstrap 5 and the `preferably` template. 
Also adds pkgdown output to gitignore to avoid it being accidently pushed in the future.
=> Feature: improve website

NEWS.md
Currently looks like this: https://epiforecasts.io/scoringutils/news/index.html
PR fixes this.
=> Bug: Correct use of markdown in News.

R/utils_data_handling.R, tests/testthat/test-utils_data_handling.R
=> get type from correct scope

R/utils.R
This PR fixes #227 by explicitly loading the metrics data set. We now get the following in a clean R session which replicates the behaviour when `scoringutils` is loaded.
```
scoringutils::score(scoringutils::example_quantile)                                                                    
The following messages were produced when checking inputs:
1.  144 values for `prediction` are NA in the data provided and the corresponding rows were removed. This may indicate a problem if unexpected.
location target_end_date target_type location_name forecast_date                 model horizon range interval_score
1:       DE      2021-05-08       Cases       Germany    2021-05-03 EuroCOVIDhub-baseline       1     0       25620.00
2:       DE      2021-05-08       Cases       Germany …
```
=> Explicitly load metrics data

R/summarise_scores.R
When by is not null we saw an issue with `add_coverage` highlighted in #223. This appears to be caused by an issue in the `data.table` code. Dropping into debug changing the call to the `mean` function to be explict (i.e `base::mean`) fixes the issue on my system. If this also causes no reversions on CI etc I'd suggest merging as aa bug fix for bleeding edge users.  I can't identify any changes in `data.table` that would lead to this change so still hypothetical that this was the system level difference.
=> Fix 223 issue with add_coverage

R/check_forecasts.R
=> Specify which column name clashes with metrics

vignettes/getting-started.Rmd
The line break in the data.table is interpreted as a line break (\n) in the string itself, leading the table to be formatted incorrectly.
=> Fix requirements table in getting-started vignette

R/pairwise-comparisons.R, tests/testthat/test-pairwise_comparison.R
avoids the pairwise comparison erroring if the specified baseline model is not present in the data (happening [in some instance](https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/actions/runs/3354890469/jobs/5558750446) at the European Forecast Hub).
It could also make sense to throw an informative error. The function can still compute useable pairwise comparisons so I thought a warning might be more appropriate here.
=> don't error if baseline model is not present

README.md
Rerenders the README. This fixes the package citation which was out of date amongst other changes that were missing from the rendered README.
=> Documentation: Update README

NEWS.md, R/check_forecasts.R, R/summarise_scores.R, R/utils.R, man/find_duplicates.Rd, man/get_forecast_unit.Rd, tests/testthat/_snaps/score.md, tests/testthat/test-score.R
This PR adds support for scoring quantile forecasts that have a sample column. It closes #242. Whilst I've added some testing to protect against issues it may be the case that the "protected" column assumptions are baked into places I have missed and so this is still dangerous.
See the following example for the new functionality:
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tidyr)
library(scoringutils)
n_sim <- 1000
epsilon <- rnorm(n_sim)
Y <- exp(epsilon)
forecasts <- expand.grid(
sigma = 1:20/10, 
quantile = c(0.01, 0.025, 1:19/20, 0.975, 0.99)
)
forecasts <- forecasts |>
as_tibble() |> …
```
=> Feature: add enhanced treatment of sample as a protected column

NEWS.md, R/pairwise-comparisons.R, R/plot.R, man/pairwise_comparison.Rd, man/plot_pairwise_comparison.Rd, tests/testthat/test-plot_pairwise_comparison.R
Simplify the function by removing the option to plot both pvalues and mean score ratios together.
=> simplify plot_pairwise_comparison()

NEWS.md, R/check_forecasts.R, R/pairwise-comparisons.R, R/score.R, R/summarise_scores.R, man/check_summary_params.Rd, man/find_duplicates.Rd, man/pairwise_comparison.Rd, man/score.Rd, man/summarise_scores.Rd
- add explanations in the documentation to make it clearer what the unit of a single forecast is and how it is inferred
=> Make forecast unit clearer

NEWS.md, R/convenience-functions.R, man/transform_forecasts.Rd
This PR performs an edit pass on the documentation for `transform_forecasts()` and the `NEWS` file. 
For the news this is mainly standardising formatting along with a few spelling corrections. 
For `transform_forecasts()` I have cleaned up a few formatting issues and expanded some of the text to try and make it very clear what is happening. I have also added `head()` calls to reduce the lenght of the rendered examples in the web docs (as these were quite long and hard to pass (at least for me)).
=> Edit pass on transform_forecasts and NEWS

.gitignore, DESCRIPTION, NEWS.md, R/summarise_scores.R, man/summarise_scores.Rd, tests/testthat/test-summarise_scores.R
This PR closes #272 by implementing an `across` argument to `summarise_scores()`. 
It also: 
- Updates the release version by one minor release (in line with other recent PRs)
- Adds a news item for this change
- Adds an example to the `summarise_scores()` documentation for this new argument. 
- Adds tests that check the equivalence of this approach as well as checking it errors when expected.
Note that because of the multiple duplicate variables in the example data `across` isn't actually as useful as you might imagine (i.e. because `target_end_date` and `horizon` define the same thing).
=> Issue 272: Add an across argument to summarise_scores()

.github/workflows/R-CMD-check.yaml, DESCRIPTION, R/correlations.R, tests/testthat/test-plot_correlation.R, tests/testthat/test-plot_interval_coverage.R, tests/testthat/test-plot_quantile_coverage.R, tests/testthat/test-plot_ranges.R
Fixes #480 
As discussed in #480, Github action checks for R 3.5 are currently failing. This is because some packages that scoringutils imports or suggests depend on R >= 3.6. 
This PR
- makes the dependency on R 3.6 explicit in DESCRIPTION
- updates gh action to use R 3.6 instead of R 3.5
- replaces `|>` with `%>%` in some tests that failed because of the new pipe operator
=> Issue #480: Fix gh action

R/correlations.R, tests/testthat/test-plot_correlation.R
We recently merged a large number of PRs into the dev branch. There was, however, one previous update to correlation() only made to dev that led checks on dev to fail after the merge marathon.
Changes I had to make were pretty minor though:
I had remove a function from correlation(), check_metric(), that should not exist anymore after all the updates.
had to rename scores to scores_quantile in a failing test that got updated on dev previously, but not in all the branches we merged.
=> Fix small issues resulting from merging several updates into dev

.github/workflows/R-CMD-check.yaml, DESCRIPTION, NEWS.md
This PR tracks changes made in #483 (apart from the added NEWS item), but targets them at main instead of the development branch. The version targeted at the develop branch has already been reviewed and approved. 
---
Fixes https://github.com/epiforecasts/scoringutils/issues/480
As discussed in https://github.com/epiforecasts/scoringutils/issues/480, Github action checks for R 3.5 are currently failing. This is because some packages that scoringutils imports or suggests depend on R >= 3.6.
This PR
- makes the dependency on R 3.6 explicit in DESCRIPTION
- updates gh action to use R 3.6 instead of R 3.5
- adds a news item
=> Issue #480: Update to R version 3.6 to fix failing gh action

R/zzz.R
Fixes #486
**Update**: After discussing this with @sbfnk I removed the specific release date and replaced it by "first quarter of 2024" as that gives us a bit more room and freedom. See https://github.com/epiforecasts/scoringutils/issues/493 for a plan of future development steps. There is still some uncertainty about which issues should be part of which release and how best to avoid too many breaking changes on CRAN. 
This PR adds a new startup message to the package warning users of upcoming changes and announcing a planned release date (February 1 2024), as well as asking them for feedback (by linking to the discussion here: https://github.com/epiforecasts/scoringutils/discussions/333)
=> Issue #486: Add startup message for a new CRAN release

.github/PULL_REQUEST_TEMPLATE.md, NEWS.md
Ruthlessly stealing from [epinowcast](https://github.com/epinowcast/epinowcast) this PR adds a PR template for new PRs to follow. 
For the last time ever, with this PR, I enjoy the freedom of writing whatever I want in a pull request. Alas, I am not to be trusted and including a PR template will hopefully include the quality of future PRs by providing an explicit checklist for things to do and think about before opening a PR.
=> Create a PR template

R/metrics-quantile.R, tests/testthat/test-metrics-quantile.R
Fixes #500 
Currently, bias_quantile() uses an internal helper function, bias_quantile_single_vector() to compute bias for a single forecast.
This helper functions throws a message if the median is not part of the quantile levels provided. That means that a single call to bias_quantile() can produce a lot of messages, as the message is repeated every time the helper is called. 
This PR 
- moves the message from the helper function to bias_quantile(), thus only getting one message for a single call to bias_quantile().
- adds a test for this
This is related to #418 (and only addresses a small part of the larger problem), but is in my opinion definitely an improvement over what we currently have.
=> Issue #500: Reduce messages in `bias_quantile()`

.Rbuildignore, R/avail_forecasts.R, R/pairwise-comparisons.R, R/pit.R, R/plot.R, R/score.R, R/summarise_scores.R, man/add_coverage.Rd, man/avail_forecasts.Rd, man/pairwise_comparison.Rd, man/pit_sample.Rd, man/plot_interval_coverage.Rd, man/plot_pit.Rd, man/plot_score_table.Rd, man/score.Rd, man/summarise_scores.Rd, tests/testthat/setup.R, vignettes/scoringutils.Rmd
This PR closes #486
During CRAN submission, we got a Note on one of CRAN's machines that CPU time > elapsed time for some examples, tests, and the vignette- this is usually the case when more than 2 cores are used. We had that issue in the past and is almost certainly linked to `data.table` (see https://github.com/Rdatatable/data.table/issues/3300 and https://github.com/Rdatatable/data.table/issues/5658). 
To "solve" this I added the line `data.table::setDTthreads(2)` before offending code. This is what was suggested in https://github.com/Rdatatable/data.table/issues/5658 by the `data.table` maintainers. 
(The PR also makes a single unrelated linting fix in the vignette)
=> Issue 486: Fix NOTEs for CRAN submission

R/metrics-binary.R, tests/testthat/test-metrics-binary.R
This PR closes #275.
Ideally we would like `logs_binary()` to be able to accept a single value as an input that then gets recycled just like any other vector in R does. The current implementation had an `ifelse()` statement there which did work for several observed values and a single predicted value, but not the other way round. 
This PR updates the code in `logs_binary()` to work with scalar values and adds tests against the function `ll()` from the `Metrics` package to verify everything is correct.
=> Issue #275: Fix handling of scalar inputs in `logs_binary()`

.github/workflows/render_readme.yaml
This PR fixes #519.
Essentially, I just copied the render readme action from [epinowcast](https://github.com/epinowcast/epinowcast/blob/main/.github/workflows/render-readme.yaml) and replaced our current version with that.
=> Issue 519: Fix failing render Readme action

R/add_coverage.R, R/default-scoring-rules.R, R/metrics-quantile.R, R/metrics-sample.R, R/pit.R, R/plot.R, R/utils.R, man/add_coverage.Rd, man/interval_coverage.Rd, man/interval_coverage_dev_quantile.Rd, man/rules_quantile.Rd, tests/testthat/_snaps/plot_correlation/plot-correlation.svg, tests/testthat/_snaps/plot_score_table/plot-score-table.svg, tests/testthat/setup.R
This PR closes #436.
We previously used the word "coverage" to describe interval coverage. This sensationally boring PR
- replaces instances of "coverage" both in the code and in the documentation to make this distinction a bit clearer. 
- updates the default scoring rules
- makes a few changes to plotting functions (`plot_score_table()`) and to `available_metrics()`. `available_metrics()` needs to be removed at some point in the future and `plot_score_table()` also needs an update, but this should be done in a different PR
Mentioning a few unrelated issues that came up: 
- There are some suggestions for code refactoring in `interval_coverage_sample()`. These should be moved to an issue. Alternatively, (and maybe preferably?) the function should be removed altogether. We're not using it …
=> Issue #436 Rename instances of "coverage" to either "interval coverage" or "quantile coverage"

R/metrics-quantile.R
The previous version had a typo: 
```
1: In (function (observed, predicted, quantile, range = 50)  :
To compute the interval coverage for a range of 50%, the quantiles 0.250.75 are required. Returning `NA`.
```
This PR fixes this so that the message now reads:
```
1: In (function (observed, predicted, quantile, range = 50)  :
To compute the interval coverage for a range of 50%, the quantiles `0.25, 0.75` are required. Returning `NA`.
```
=> Fix error message for `interval_coverage_quantile()`

.github/workflows/render_readme.yaml, DESCRIPTION, NEWS.md, README.Rmd
This PR closes #535.
It does so by setting the development version (four components) as [done in the `usethis` package](https://usethis.r-lib.org/reference/use_version.html).
It also adds a note for the user to clarify which version of the documentation they're looking at. This is mostly to help people arriving from a search engine.
=> Issue #535: Create pkgdown docs for stable and dev versions

.github/workflows/render_readme.yaml
This PR closes #560.
This PR fixes render_readme.yaml by adding any newly created figures to git along with `readme.md`.
=> Issue 560: Fix render_readme

.github/dependabot.yml
-------
This PR closes #564.
It does so by adding a bot that keeps the action up to date. No need for a news item / package checks etc.
=> Issue #564: add dependabot to keep GitHub Actions up to date

.github/workflows/pkgdown.yaml
-------
This PR closes #566.
It stops cleaning the repo when deploying.
No news item/checks etc. needed as package code unaffected.
=> Issue #566: don't clean upon pkgdown deployment.

README.Rmd, README.md
-------
This PR closes #547.
It explicitly cites the preprint and adds a "Package overview" section header.
Seems to small a change for a news item.
=> Issue #547: update package description in README

.github/workflows/pkgdown.yaml, .github/workflows/render_readme.yaml
Merges main into develop so as to have the changes from PR #567 there (we need them in both branches).
=> Issue #566: don't clean upon pkgdown deployment (this time on develop)

R/utils_data_handling.R, tests/testthat/test-utils_data_handling.R
This PR closes https://github.com/epiforecasts/scoringutils/issues/543
The problem is caused by concatenating a `seq` of numbers inside a vector. Later down the line in the metric calculations, a function is checking that the quantile vector is symmetrical by looking at whether x == 1- x and finding an error. There is a small numerical difference between x and 1 - x as you can see below. Rounding at 10 digits fixes this and the example in the issue runs as expected.
```
> x <- c(0.01, 0.025, seq(0.05, 0.95, 0.05), 0.975, 0.99)
> x[1]
[1] 0.01
> x[23]
[1] 0.99
> x[1] == 1 - x[23]
[1] FALSE
> x[1] - (1 - x[23])
[1] -8.673617e-18
> round(x[1], 10) == round(1 - x[23], 10)
[1] TRUE
```
In addition to this I now concatenate the user's quantiles vector with 1 - quantile vector. That way if the …
=> Issue 557: Fix small numerical issue in sample_to_quantile()

README.Rmd, README.md
In #563 @sbfnk introduced new functionality to post users at the alternative version of the docs to the one they are currently viewing. However, if they are not on the HTML docs then there is currently no link to the current version of the HTML docs that they are looking at. It could be nice if this were the case. 
This PR adds this. I think worth some discussion to check it makes sense .
=> Add current docs link to README

R/add_coverage.R, R/convenience-functions.R, tests/testthat/test-add_coverage.R, tests/testthat/test-as_forecast.R, tests/testthat/test-convenience-functions.R
This PR closes #559.
`add_coverage()` used to return a `data.table()`, even if it was called on an object of class `forecast_quantile`. This was due to internal computations: the function `quantile_to_interval()` returns a `data.table` and when merging the newly computed columns with the existing data, a `data.table` was produced. 
In addition, `transform_forecasts()` had a similar issue. This was due to a call to `as.data.table()`. 
This PR 
- switches the order in which the two datasets are passed to `merge()`, solving the issue for `add_coverage()`
- replaces `as.data.table()` with `as_forecast()` for `transform_forecasts()`
- Adds a unit test for both
- Adds an additional, mostly unrelated unit test to check that running `as_forecast()` twice produces the same object. I added this …
=> Issue #559: Ensure output of `add_coverage()` is an object of class forecast_quantile

NEWS.md, R/get_-functions.R, R/pairwise-comparisons.R, R/plot.R, tests/testthat/test-pairwise_comparison.R, tests/testthat/test-summarise_scores.R
This PR closes #475.
It renames the output columns for pairwise comparisons to contain the score.
=> Issue #475: rename output columns for pairwise comparisons

R/convenience-functions.R, tests/testthat/test-convenience-functions.R
This PR closes #580 
`set_forecast_unit()` can introduce issues, when called after `as_forecast()`. For example, you could drop columns that are necessary to unambiguously define a single forecast, leading to duplicates. Therefore, `set_forecast_unit()` should validate that an object that was previously an object of class `forecast_` is still one. 
It doesn't validate objects that haven't previously been objects of class `forecast_`. That would mean that `set_forecast_unit()` would have to call `as_forecast()`, but this might lead to errors where there shouldn't be any (also then having two different functions for `set_forecast_unit()` and `as_forecast()` wouldn't make much sense). 
This PR therefore adds a line that checks if the input was an object of class `forecast_*` and if so, runs …
=> Issue #580 validate output of `set_forecast_unit()` where appropriate

tests/testthat/_snaps/utils_data_handling.md
This PR fixes #619. 
As mentioned by @seabbs in #616, the recent update of data.table requires an update to our test snaps. This PR fixes this.
=> Issue #619: Update tests after data.table update

DESCRIPTION, README.md, _pkgdown.yml, man/scoringutils-package.Rd
This PR commits changes due to an update in roxygen. It does that because I'm a good developer and would never mix unrelated changes into other PRs... 👀 
There is another unrelated change to the Readme.md file. This comes from the update to the print method in #592 and the automatic CI update of the readme. It actually uncovers an error that we need to fix, namely `score()` does not respect previous output from `add_coverage()`. I opened an issue for this (#623)
=> Unrelated changes - Roxygen update

R/utils.R, tests/testthat/test-utils.R
This PR closes #620 
We recently introduced a print method for forecast objects. This print method was calling `get_forecast_type()` and `get_forecast_unit()` internally which require the object to pass basic validations. If these didn't pass, `print()` would error. 
This PR therefore 
- updates the print method to 
- run `validate_error()` first and catch any error
- print any error as part of the output
- wraps `get_forecast_type()` and `get_forecast_unit()` in `try` statements as well and catches errors
- moves the `score_names` print section to the end. (If we implement #631 then we can likely get rid of that completely, because then no forecast object should have any scores)
- adds a new unit test
=> Issue #620: Allow print method to fail gracefully

R/plot.R, tests/testthat/test-plot_interval_coverage.R
`plot_interval_coverage()` deletes the `quantile_level` column (and associated coverage values) to avoid plotting duplicated lines (since every interval range appears twice as there are two quantile levels per interval). This PR makes sure that `plot_interval_coverage()` does its thing on a copy of the data.
=> Fix issue where `plot_interval_coverage()` drops columns

NEWS.md, R/convenience-functions.R, tests/testthat/test-convenience-functions.R
This PR closes #640
Currently, `set_forecast_unit()` warns if a column specified in `forecast_unit` is not found in the data, but proceeds nevertheless and ignores offending entries. This may be confusing and an error seems a much clearer option. As discussed in #640, this PR updates the input checks to make sure that the function only executes if all specified columns are actually there. 
The PR also updates tests to reflect that change.
=> Issue #640: Update set forecast unit to error if any specified column is not found in the data

R/pit.R
I noticed that the `pit_example()` function uses quite a high number of replications/samples in its example. This PR reduces that.
=> reduce number of samples in pit examples

DESCRIPTION
This PR closes #614.
This PR
- removes the `lifecycle` package from imports as we aren't using it anymore (at least for now)
- adds a version requirement to `testthat` as suggested in #614 
On that note, we should maybe configure our `R CMD check` CI to fail when encountering a note. I think it currently let's Notes pass.
=> Issue #614 - update package imports

R/correlations.R, man/get_correlations.Rd, tests/testthat/test-get_correlations.R
This PR closes #672.
I noticed a weird error in #672. The error comes from the fact that if you passed unsummarised scores to `get_correlations()` then it removed the coverage columns because those are not numeric. 
This PR 
- drops the code that does that and lets `cor()` handle any exceptions. 
- adds unit tests with something that would previously have produced an error 
- adds a `...` argument to `get_correlations()`. Not sure how many people will actually want to pass additional args to `cor()` but then again why not...
=> Issue #672 - Fix `get_correlations()`

R/forecast.R, tests/testthat/test-forecast.R
This PR closes #677.
This PR closes #603.
The change to the new format may be somewhat confusing for users in a few particular circumstances. For example, if you have a `quantile` column instead of a `quantile_level` column then `scoringutils` now thinks this is just any normal column and classifies your forecast as a point forecast. Or if you want to score a binary forecast, but forget to make your observed values a factor, then you'll end up with a point forecast again. 
This PR
- adds once-per-session warnings for both of these things
- adds tests to check that
=> Issue #677 - Warn users if they use an outdated format

R/plot.R, tests/testthat/test-plot_correlation.R
This PR closes #245. 
#245 notes that you don't get a very informative error message if you pass something that's not the output of `get_correlations()` to `plot_correlations()`. 
This PR
- adds additional input checks to make sure that
- the input is a data.frame
- there is a `metric` column and all correlations are <= 1
- adds a test
I assume there would be potential to make all of this more sophisticated, but I think for now it should do the trick. 
=> Issue #245 - add additional input checks to `plot_correlations()`

R/plot.R, man/plot_heatmap.Rd, tests/testthat/test-plot_heatmap.R
Cleaning up plotting functions. 
This PR
- adds input checks to `plot_heatmap()`
- removes the forced `round()` statement in the code and instead makes the user responsible for rounding. I really think it is these small breaking changes that users will love us for... One alternative would have been an additional `digits` argument (we do that for `get_correlations()`, but not for `plot_correlations()` for example). 
Another slightly more radical step would be to remove the function altogether and replace it with a vignette entry. I'm not really sure the function adds that much over "you go ahead and write your `ggplot` code and here is an example for how you could do that if you wanted". What do you think?
=> Issue #355 - Add input checks to `plot_heatmap`

R/plot.R
Related to #355. 
Very minor update to the input checks. `assert_subset()` has an implicit type check, so there is no need to check whether x and y are strings. Also logicals should only be of length one.
=> Issue #355 - Update input checks for `plot_forecast_counts()`

R/get_-functions.R, man/get_forecast_counts.Rd
We started replacing `by = NULL` with `by = get_forecast_unit(data)` to increase clarity for users. This PR cleans up the last place where this is not the case yet and updates the docs.
=> Replace `by = NULL` with `by = get_forecast_unit(data)` in `get_forecast_counts()`

R/check-input-helpers.R
This PR closes #744.
From #744: 
> I found a very weird error when analysing some data: 
```
Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can add this new column by reference. At an earlier point, this data.table has been copied by R (or was created manually using structure() or similar). Avoid names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. If this message doesn't help, please report your use case to the data.table issue tracker so the root cause can be fixed or this message improved. ” 
```
> This has something to do with a mix of `dplyr` and `data.table` and occurred when I called `mutate()` on a forecast object. I was …
=> Issue #744 - Fix weird .internal.selfref error by making a copy in `check_number_per_forecast()`

README.Rmd, README.md
This PR fixes two small issues in the Readme: 
- The readme currently uses `head(data, 2)` to print the first two rows of a forecast object. This means that the forecast object fails validation (as it only has two rows with `NA` values left. This PR changes `head(data, 2)` to `print(data, 2)` which solves the problem. 
- The link to the revised paper should belong to "revised version" not "updated version". I slightly adapted the link.
=> Fix small typo in the readme

R/get_-functions.R, R/summarise_scores.R, R/utils.R, R/utils_data_handling.R, tests/testthat/test-summarise_scores.R, tests/testthat/test-utils.R
As discussed in #447, some functions lack input checks. This is the third PR that adds more checks. 
This PR
- simplifies input checks in `summarise_scores()`
- slightly updates the error message in `get_metrics()` + associated tests
- adds input checks to 
- `merge_pred_and_obs()`
- `sample_to_quantile()`
- `run_safely()`
- replaces some `data.table::` calls with `ensure_data.table()`
**Further thoughts**: 
- there is an argument to be made that `sample_to_quantile()` should require a validated `forecast_sample`. I opened a separate issue for this: https://github.com/epiforecasts/scoringutils/issues/755
-
=> Issue #447 - Add even more input checks

R/metrics-quantile.R, man/quantile_score.Rd, tests/testthat/test-metrics-quantile.R
This PR closes #761.
Previously, the function `quantile_score()` inherited its arguments from `wis()`, but the actual format it expected was different from the one used by the other quantile-based metrics. 
The function used to expect a vector of observed values and a single vector with predicted values and a single quantile level. This is in contrast to the other quantile-based functions, which usually expect a matrix of predicted values and are also able to accept several quantile levels. 
This PR changes the expected input format of `quantile_score()` such that it conforms to what the other functions accept. Instead of computing the quantile score for a single vector, it now computes the score for several quantile forecasts and returns an average score. One implication of this is that …
=> Issue #761 - Update input checks and docs for `quantile_score()`

R/convenience-functions.R, R/forecast.R, R/get_-functions.R, R/pit.R, R/print.R, R/score.R, R/utils_data_handling.R, man/apply_metrics.Rd, man/get_coverage.Rd, man/get_forecast_counts.Rd, man/get_pit.Rd, man/interval_long_to_quantile.Rd, man/pit_sample.Rd, man/quantile_to_interval.Rd, man/sample_to_interval_long.Rd, man/sample_to_quantile.Rd, man/score.Rd, man/transform_forecasts.Rd, man/validate_forecast.Rd, man/validate_general.Rd, tests/testthat/test-merge_pred_and_obs.R, tests/testthat/test-metrics-point.R, tests/testthat/test-pairwise_comparison.R, tests/testthat/test-score.R
This PR closes #<issue-number>.
- Changed the argument from `data` to `forecast` in the following functions
- `score()`
- `validate_forecast()` (but not `validate_general()`)
- `get_forecast_counts()`
- `get_pit()`
- `sample_to_quantile()`
- `interval_long_to_quantile()`
- `quantile_to_interval()`
- `transform_forecasts()`
- updated tests where necessary
The `validate_general()` is a bit of an edge case. 
Context: 
- the function does all the validations that are the same for the different `validate_forecast()` methods
- It is exported for two reasons: 
- it's an S3 method and I only recently learned you could have them be internal
- it could be useful for people who want to create their own classes and run their own checks
Since the function doesn't _require_ a `forecast` object …
=> change `data` to `forecast` in `score()` and update related tests

R/check-input-helpers.R, R/forecast.R, R/get_-functions.R, man/check_duplicates.Rd, man/get_duplicate_forecasts.Rd
This PR closes #693.
As described in #693. This PR removes the `forecast_unit` arg from 
- `get_duplicate_forecasts()` 
- `check_duplicates()` (which maybe should be `check_duplicate_forecasts()`, but then again it's internal anyway)
=> Issue #693 - Remove `forecast_unit` argument from `get_duplicate_forecasts()`

R/metrics-quantile.R, man/bias_quantile.Rd
This PR closes #309.
This PR makes a small change to the documentation of `bias_quantile()`, making sure that the verbal description (smaller/greater than or equal to) matches the >= and <= in the formula.
=> Issue #309 - fix error in bias quantile documentation

R/get_-functions.R, R/summarise_scores.R, man/get_metrics.Rd, tests/testthat/test-summarise_scores.R
This PR closes #804. 
As discussed in #804, `summarise_scores()` currently doesn't produce a helpful warning when you pass in a `data.frame`. This PR updates `summarise_score()` such that it also handles a `data.frame` as input (provided, that a `metrics` attribute is present. 
Thank you to @damonbayer for raising this point!
=> Ensure that summarise_scores() works with a data.frame or similar

.github/workflows/render_readme.yaml, README.Rmd
This PR closes #855.
As discussed in the issue, this PR steals the render-readme yaml from the excellent `epinowcast` package.
=> Issue #855 - render readme as PR

R/metrics-quantile.R, man/quantile_score.Rd, vignettes/scoring-rules.Rmd
Got this `R CMD check` error:
```
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
! LaTeX Error: Unicode character − (U+2212)
not set up for use with LaTeX.
```
Probably, this is a deficiency of the system (a Docker container) where I'm running `R CMD check`. But anyway, a hyphen seems more appropriate here.
=> Use ASCII hypen

R/score.R, man/new_scores.Rd
Currently seeing this `NOTE` in `R CMD check` on devel:
```
* checking Rd cross-references ... NOTE
Found the following Rd file(s) with Rd \link{} targets missing package
anchors:
new_scores.Rd: as.data.table
```
=> ns-qualify as.data.table() for R CMD check

R/utils_data_handling.R, tests/testthat/test-metrics-quantile.R
This PR closes #827.
As discussed in #827, `wis()` didn't give a very informative error when there were no valid quantiles left. This PR changes `quantile_to_interval_dataframe` to throw an error when there are no valid intervals. This function is an internal function and I think you'd never want it to succeed if it wasn't able to produce a single valid forecast interval.
=> issue #827 - Improve error handling for wis()

R/forecast.R, tests/testthat/test-forecast.R, tests/testthat/test-get_-functions.R
The `"forecast_sample"`, etc. are a subclass of `"forecast"` so the order in the class attribute needs to be reversed for correct dispatch.
=> Fix inheritance order

R/convenience-functions.R, R/correlations.R, R/default-scoring-rules.R, R/get_-functions.R, R/pairwise-comparisons.R, R/plot.R, R/summarise_scores.R, R/utils_data_handling.R, man/customise_metric.Rd, man/get_correlations.Rd, man/get_forecast_counts.Rd, man/get_pairwise_comparisons.Rd, man/log_shift.Rd, man/plot_correlations.Rd, man/plot_forecast_counts.Rd, man/plot_heatmap.Rd, man/plot_pairwise_comparisons.Rd, man/plot_pit.Rd, man/plot_wis.Rd, man/sample_to_quantile.Rd, man/set_forecast_unit.Rd, man/summarise_scores.Rd
This PR closes #530.
As discussed in #530, this PR updates examples to use the pipe operator consistently and conform to the happy path outlined for users.
=> Issue #530 - Clarify workflow in examples

R/forecast.R
This ensures that object manipulated by [ via dplyr function are still validated. See the report in 
https://github.com/epiforecasts/scoringutils/pull/884#issuecomment-2293785836.
``` r
library(scoringutils)
#> Note: scoringutils is currently undergoing major development changes (with an update planned for the first quarter of 2024). We would very much appreciate your opinions and feedback on what should be included in this major update: https://github.com/epiforecasts/scoringutils/discussions/333
f <- as_forecast_quantile(example_quantile)
#> ℹ Some rows containing NA values may be removed. This is fine if not
#>   unexpected.
f <- f |> 
dplyr::select(-observed)
#> Warning: ! Error in validating forecast object: Error : Assertion on 'data' failed:
#>   Column 'observed' not found in …
```
=> Use stricter check to bypass validation of x[]

R/pit.R, R/plot.R, man/get_metrics.forecast_point.Rd, man/pit_sample.Rd, tests/testthat/_snaps/plot_pit/plot-pit-integer.svg, tests/testthat/_snaps/plot_pit/plot-pit-quantile-2.svg, tests/testthat/_snaps/plot_pit/plot-pit-quantile.svg, tests/testthat/_snaps/plot_pit/plot-pit-sample.svg
This PR closes #359.
Most things look correct to me - I have addressed the [issue of `num_bins` not being reflected](https://github.com/epiforecasts/scoringutils/issues/359#issuecomment-2344721559) by ensuring 0 and 1 are always included as boundaries and cleaned up some of the other code/docs (see individual commit messages).
There were two broader questions raised by this work:
- the way `get_pit` and `plot_pit` interact makes addressing https://github.com/epiforecasts/scoringutils/issues/913 impossible - the nonrandomised method requires the bins to be known at the time the PIT is calculated
- the way quantiles are plotted when the breaks don't coincide with the quantiles levels in the data doesn't really makes sense (only the ones that coincide are plotted). It might be nice here to …
=> 359: Check PIT

R/score.R, tests/testthat/test-score.R
This PR closes #931 
As discussed in #931, manipulating `scores` objects caused a warning due to the use of `attr()` in `[.scores`. This PR replaces `attr()` with `setatrr()` and adds some tests.
=> #931 - Fix data.table issue caused by `attr()`

R/get_-functions.R, tests/testthat/test-get_-functions.R
I realised that we currently don't handle `by = NULL` in `get_forecast_counts()`. This drive-by PR updates the corresponding `assert` statement, adds a test and also removes unnecessary `as_forecast_<type>` statements from the same test file (#unrelated-changes!)
=> Improve error handling for `get_forecast_counts()` and streamline some tests

NEWS.md, R/metrics-quantile.R, man/wis.Rd, tests/testthat/test-class-forecast-quantile.R
This PR closes #926.
As discussed in #926, this PR lets `wis()` error by default if not all quantile levels form valid prediction intervals. I realised that there was a `na.rm` argument already (it was just set to `TRUE`). I think `FALSE` is a better default. 
If the quantile levels aren't symmetric, the function errors immediately. 
(Note that there is a second way in which `na.rm` can be relevant: if a specific quantile is missing for a forecast. With `na.rm = TRUE` `NA` values will be dropped and otherwise the output is `NA`.)
=> Handling case in WIS where quantile levels don't form valid intervals

R/get-forecast-type.R, tests/testthat/test-get-forecast-type.R
This PR closes #952.
Updates the function to check for a class named `forecast_` rather than only checking the first class
=> Issuel #952 - Fix get_forecast_type

R/class-forecast.R, tests/testthat/test-class-forecast-nominal.R, tests/testthat/test-class-forecast.R
This PR mostly gives up on #935. 
Previously, just calling `example_nominal` caused an error due to the subsetting that's happening within `print.data.table`. 
This function just removes the function that's responsible for it and adds a test. 
The issue that manipulating columns of a dt causes random printing still persists, sadly. But at least on error anymore.
=> Remove function that resulted in an error when called from within print.data.table()

NEWS.md, vignettes/scoring-rules.Rmd
This PR closes #969 
* Fix mathematical error in interval coverage section
* Fix some spelling errors
* NOTE: linter failed, but unrelated to PR
=> Vignette typos

NEWS.md, R/metrics-sample.R, tests/testthat/test-metrics-sample.R
=> 973: underprediction/overprediction/etc. fails if all observations are above/below the medians

NEWS.md, R/pairwise-comparisons.R, man/add_relative_skill.Rd, man/compare_forecasts.Rd, tests/testthat/test-pairwise_comparison.R
This PR closes #978
As suggested in #978, this PR adds an option to make the computation of p values optional.
=> Make calculation of p-vals options in `get_pairwise_comparisons()`

NEWS.md, R/metrics-nominal.R
This PR closes #996 
As discussed in #996, this PR allows for some numeric imprecision when checking whether all probabilities sum to 1.
=> Allow for numeric imprecision for ordinal forecasts

DESCRIPTION, NEWS.md
This PR closes #1005.
For scoring ordinal forecasts, we require functionality that was introduced in `scoringRules v1.1.2`. This PR therefore updates the dependency accordingly,
=> Issue #1005 - Update dependency on scoringRules to >=1.1.2 

NEWS.md, R/metrics-sample.R
This PR closes #1009.
Whilst there also fixes another bug later on.
=> 1009: don't round for PIT histograms
